language: java

jdk:
  - oraclejdk8

services: mongodb


script:
  - mvn test -B -Dspring.data.mongodb.host=localhost

before_deploy:
  - mkdir dist
  - mv target/api-*.jar dist


deploy:
  provider: s3
  bucket: "codepipeline-doesuanota"
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  skip_cleanup: true
  local_dir: dist